# Generated by Django 4.1.4 on 2022-12-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_comment_rating_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='_rating_comment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='_rating_post',
        ),
        migrations.AddField(
            model_name='comment',
            name='rating_comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='rating_post',
            field=models.IntegerField(default=0),
        ),
    ]
