# Generated by Django 4.1.4 on 2022-12-20 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_post_one_to_many_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='one_to_many_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.author'),
        ),
    ]
