# Generated by Django 4.1.4 on 2023-01-28 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0006_alter_post_one_to_many_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('in_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(through='news.AuthorCategory', to=settings.AUTH_USER_MODEL),
        ),
    ]
